### ISSUE TITLE
Scanning is taking long time after 0.9.9->0.9.10 upgrade

### ISSUE THREAD

**Issue by mityayak** [ronmamo/reflections#100]
We are experiencing scan time increase, like 2-3 times after upgrading from 0.9.9 version to 0.9.10
While enabling logging debug I can see the difference in behaviour:
In 0.9.10 version we are scanning for non-classes and have tons of those messages in a log:
FINE: could not scan file my/package/Resources_nl.properties in url file:/D:/my/path/buildtree/ with scanner TypeAnnotationsScanner
Nov 02, 2015 2:54:41 PM org.reflections.Reflections scan
FINE: could not scan file my/package/Resources_nl.properties in url file:/D:/my/path/buildtree/ with scanner SubTypesScanner
Nov 02, 2015 2:54:41 PM org.reflections.Reflections scan
While with 0.9.9 we are not having those logs at all, i.e. we are not doing non-classes scanning.
I'm not sure why scanning is happening at all with 0.9.10 since 'my.package' is not added into ConfigurationBuilder

**Comment by matthiasbraun** [comment]
You could add an input filter that only accepts files containing ".class", like this:

`new ConfigurationBuilder().filterInputsBy(new Predicate<String>() {
    @Override
    public boolean apply(String input) {
        return input.contains(".class");
    }
});`
