### ISSUE TITLE
Is it possible to include a negation modifier?

### ISSUE THREAD

**Issue by marcgise** [ronmamo/reflections#112]
For instance this query: all the public getter methods but not static from a class:

ReflectionUtils.getMethods(myClass, ReflectionUtils.withModifier(Modifier.PUBLIC), ReflectionUtils.withoutModifier(Modifier.STATIC), ReflectionUtils.withPrefix("get"));

**Comment by thomaseizinger** [comment]
You can use the `Predicates` utility class from guava to negative the predicate using `Predicates#not`.

**Comment by UserProgrammer** [comment]
> You can use the `Predicates` utility class from guava to negative the predicate using `Predicates#not`.

Worked as desired, thanks!
