### ISSUE TITLE
What's MethodAnnotationsScanner?

### ISSUE THREAD

**Issue by grimimirg** [ronmamo/reflections#114]
I have to know what's that because I'm stuck with the exception: `org.reflections.ReflectionsException: Scanner MethodAnnotationsScanner was not configured` while I'm trying to get annotated method using `getMethodsAnnotatedWith()`.

This is my easy piece of code: 
`Reflections reflections = new Reflections(ApplicationContext.rootContext());
Set<Method> annotatedMethods = reflections.getMethodsAnnotatedWith(Column.class);`

My exception is in `public Multimap<String, String> get(String index)`

Thanks!

**Comment by ronmamo** [comment]
new Reflections(my-package, /*add this->*/new MethodAnnotationScanner(), other-scanners, ...)

**Comment by abccbaandy** [comment]
this should be in usage doc

**Comment by BlackSunshine-manage** [comment]
> 
> 
> new Reflections(my-package, /_add this->_/new MethodAnnotationScanner(), other-scanners, ...)

That good lib man, ty from russian users!
