### ISSUE TITLE
Empty list returned for classes on Android

### ISSUE THREAD

**Issue by akbiggs** [ronmamo/reflections#115]
I am trying to use reflections on Android, however I am running into the same issue as reported in this SO post http://stackoverflow.com/questions/32772229/reflections-library-returns-empty-list-in-android

Does Reflections support Android?

**Comment by delix** [comment]
I started debugging this after I got the same error, I've narrowed it down `ClasspathHelper.forPackage("my.package")` not returning (finding) the classes as resources. Will continue with the debugging.

**Comment by nasht00** [comment]
I see this thread is kind of old. Is there any news? Should we consider this "wontfix"?

**Comment by hshahdoost** [comment]
This is actually a huge flaw, I'm wondering how come it hasn't been fixed yet
