### ISSUE TITLE
ClasspathHelper should build relative URL (drools compatibility)

### ISSUE THREAD

**Issue by ge0ffrey** [ronmamo/reflections#116]
The class `ClasspathHelper` does this:

    result.add(new URL(url.toExternalForm().substring(0, index)));

but this means if the original url was using an non-default protocol (such as "mfs:/" for kjar resources in drools), it will fail.
The solution is to do something like this:

    result.add(new URL(url, url.toExternalForm().substring(0, index)));

**Comment by ge0ffrey** [comment]
Please merge this PR to fix this:
  https://github.com/ronmamo/reflections/pull/118

**Comment by ronmamo** [comment]
merged

**Comment by ge0ffrey** [comment]
Thanks for merging!
