### ISSUE TITLE
Defect in DefaultUrlTypes causes package discovery to fail

### ISSUE THREAD

**Issue by jameskennedy** [ronmamo/reflections#121]
Because Vfs.DefaultUrlTypes.jarFile and Vfs.DefaultUrlTypes.directory test url.toExternalForm().contains(".jar") instead of url.toExternalForm().endsWith(".jar") Vfs.fromURL(URL, List<UrlType>) will fail to read a legitimate directory url like "file:/Users/jarvis.jeeves/git/com.jarvis.app/target/classes/"

We don't really have the ability to use custom UrlTypes as a workaround because we are using Reflections via another library (io.swagger BeanConfig). 

A fix would be much appreciated since we really can't change our project directory structure to avoid containing ".jar".

**Comment by jrjarrett** [comment]
I also found this in issue #76
