### ISSUE TITLE
enums aren't picked up with getSubTypesOf(Object.class)

### ISSUE THREAD

**Issue by szymonwartak** [ronmamo/reflections#126]
enums are subType of java.lang.Object but they're not being picked up:

```
 new Reflections("<package>", new SubTypesScanner(false)).getSubTypesOf(Object.class)
```

**Comment by stuz5000** [comment]
reflections.getSubTypesOf(Object.class) doesn't seem to find *any* results where reflections.getSubTypesOf(SomeClass.class) does.

It seems to be an issue with scanning for Object. Is this an oversight?

**Comment by dthulson** [comment]
I have this issue as well.  I have worked around it by asking for subtypes of both Enum.class and Object.class where necessary but given Enum extends Object, they should be included right?
