### ISSUE TITLE
Get all classes from package

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [ronmamo/reflections#13]
I have seen the example like 
   Set<Class<? extends Module>> modules = reflections.getSubTypesOf(com.google.inject.Module.class);

But, I'd like to get all classes from package wihout especified the class, something like

List<Class> clazz = reflections.getClassFromPackage("com.someproject.model");

is it possible? how can I do that with Reflection library?

**Comment by stuz5000** [comment]
@ronmamo I don't agree that acting on all class in a package is an invalid use case.
I have a package and I want to register *all* class in this package with a serialization framework. The classes have no common bases except Object and require no special annotations.

**Comment by ronmamo** [comment]
Good point. I agree.
It is a legitimate metadata.
