### ISSUE TITLE
Is there a JKD1.6 version?

### ISSUE THREAD

**Issue by hedleyyan** [ronmamo/reflections#133]
When I use this .jar in my project which java compiler is JKD1.6, it throws one exception:

`Exception in thread "main" java.lang.UnsupportedClassVersionError: reflection/Test : Unsupported major.minor version 51.0`

**Comment by tylerwmarrs** [comment]
Any update on this?

**Comment by tylerwmarrs** [comment]
I manually compiled it against jdk1.6 which involves downloading the source and manipulating the pom.xml file. The test suite runs fine against the latest commit of 6921115.

**Comment by ronmamo** [comment]
compiled with java 7
