### ISSUE TITLE
License

### ISSUE THREAD

**Issue by afkham** [ronmamo/reflections#134]
In the main pom.xml, there are two licenses indicated, WTFPL & BSD. However, on the GitHub home page of this project, at the bottom of the page, it says the code is licensed under WTFPL. So my question is, what is the applicable license? We have a concern in using this library because our code is Apache Licensed and WTFPL is not OSI approved, so there is a bit of a legal grey area. Please clarify whether this library is dual licensed under WTFPL & BSD or is it licensed only under WTFPL.

Thanks
Azeez

**Comment by kcooney** [comment]
I tried to clarify this in pull #107

**Comment by afkham** [comment]
Fixed

**Comment by kcooney** [comment]
@afkham pull #107 hasn't been merged, so I don't think this issue is fixed

**Comment by afkham** [comment]
Sorry, the PR hasn't been merged.

**Comment by ronmamo** [comment]
License is WTFPL.
I would even use a shorter version of it (if there was).
This library is published as an act of giving and generosity, from developers to developers. All the licensing governance mumble jumble does not concern me.
Please feel free to use it, and to contribute to the developers community in the same manner. One solution is to fork it and use another license.
