### ISSUE TITLE
getTypesAnnotatedWith() is not working with Lambda

### ISSUE THREAD

**Issue by tzvatot** [ronmamo/reflections#135]
Using getTypesAnnotatedWith() method, it seems it misses classes that are annotated by the annotation provided as argument, in case they contain a lambda expression.

``` java
package a;

import static org.testng.AssertJUnit.assertFalse;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import org.reflections.Reflections;
import org.springframework.stereotype.Component;
import org.testng.annotations.Test;

@Component
public class ReflectionLambdaTest {

    @Test
    public void test() {
        Reflections ref = new Reflections("a");
        Set<Class<?>> res = ref.getTypesAnnotatedWith(Component.class);
        List<String> l = new ArrayList<>();
        // l.stream().forEach(a -> a.toCharArray()); // <-- if you unmark this, the test fails
        assertFalse(res.isEmpty());
    }

}
```

**Comment by Spectrality** [comment]
There is also an issue with Lambdas and the Java 8 forEach method when using the getSubTypesOf() method as well. In testing, I noticed that my classes cannot be found using that method if there are Lambdas or forEach calls in the class, but if they are commented out they are easily found.

**Comment by tzvatot** [comment]
After upgrading javassist to latest (3.20.0-GA instead of 3.15.0-GA) it worked.

**Comment by igolus** [comment]
Hello, 

When using maven, update the dependencies like that (Worked for me):

		<dependency>
			<groupId>org.reflections</groupId>
			<artifactId>reflections</artifactId>
			<version>0.9.10</version>

			<exclusions>
				<exclusion>
					<groupId>org.javassist</groupId>
					<artifactId>javassist</artifactId>
				</exclusion>
			</exclusions>

		</dependency>
		
		<dependency>
			<groupId>org.javassist</groupId>
			<artifactId>javassist</artifactId>
			<version>3.20.0-GA</version>
		</dependency>
