### ISSUE TITLE
Resource pattern filter for complete resource path

### ISSUE THREAD

**Issue by cosmin-marginean** [ronmamo/reflections#148]
We have a use case where a filter like this is essential

```
reflections.getResources("folder/.*");
```

After some investigation though, we realised that for a resource `folder/file1.txt`, the regex is only tested against the `file.txt` rather than the whole path. 

What this means is that we can't use this process to obtain all resources within a specific level in the resource hierarchy/structure.

**Comment by norbertwnuk** [comment]
You can customize ResourcesScanner to achieve such behavior:

```
public class ResourcesScanner extends org.reflections.scanners.ResourcesScanner {
	@Override
	public Object scan(Vfs.File file, Object classObject) {
		getStore().put(file.getRelativePath(), file.getRelativePath());
		return classObject;
	}
}
```

**Comment by ronmamo** [comment]
Either write another scanner as @norbertwnuk mentioned, or query the store directly `reflections.getStore().get(ResourcesScanner.class.getSimpleName()`

**Comment by sschuberth** [comment]
> public class ResourcesScanner extends org.reflections.scanners.ResourcesScanner {

How would you actually do this now that `Scanners.Resources` is an `enum` member (and thus `final`)?
