### ISSUE TITLE
Java 8 reflection fails

### ISSUE THREAD

**Issue by aldenquimby** [ronmamo/reflections#15]
Trying to scan a class that uses a lambda expression fails. Specifically, the error I'm seeing is:

```
org.reflections.Reflections - could not scan file _ in url _ with scanner SubTypesScanner
org.reflections.Reflections - could not scan file _ in url _ with scanner TypeAnnotationsScanner
```

Digging into the `AbstractScanner.scan` method, the inner exception is:

```
java.io.IOException: invalid constant type: 18 at 8
```

**Comment by tzvatot** [comment]
Facing the same issue, using javassist 3.20.0-GA and reflections 0.9.10.
