### ISSUE TITLE
When will 9.11 get published to maven repo?

### ISSUE THREAD

**Issue by jameskennedy** [ronmamo/reflections#154]
My team is relying on a fix that went into 9.11. It would be great if we didn't have to keep depending on our own SNAPSHOT artifact.

**Comment by UnAfraid** [comment]
I also wanted to use this version can you please push it at least to snapshots repo?

**Comment by renatoathaydes** [comment]
If you guys release it soon, can you please upgrade your Guava version? It's getting old fast :)

**Comment by jameskennedy** [comment]
Reposting "My team is relying on a fix that went into 9.11. It would be great if we didn't have to keep depending on our own SNAPSHOT artifact."

Would love to see 9.11 get published to Maven.

**Comment by ronmamo** [comment]
Published 0.9.11

**Comment by daniel-beck** [comment]
Why was 0.9.11 re-released two weeks later, on March 24?
