### ISSUE TITLE
[Improvement] JsonSerializer cache Gson instance

### ISSUE THREAD

**Issue by cordisvictor** [ronmamo/reflections#160]
Gson is thread-safe and since it is instantiated in the param-less "getGson()" method, it can be a static+final component, thus dropping the need for the lazy getGson() and also allowing it to be shared across multiple JsonSerializers.

**Comment by ronmamo** [comment]
Pull request are welcomed. Closing this and #161 for now.

**Comment by cordisvictor** [comment]
403 when trying to push pull request branch on this repo.

**Comment by ljacqu** [comment]
You need to fork the repo

**Comment by cordisvictor** [comment]
Thanks!

**Comment by cordisvictor** [comment]
This issue was closed, but I provided pull/176 request with the proposed refactoring.
