### ISSUE TITLE
getTypesAnnotatedWith not work when scaned class is not on classloader.

### ISSUE THREAD

**Issue by vipcxj** [ronmamo/reflections#162]
If I want to scan a lot of jars. Then I add their path to the Configuration object. Scanning is successful. However the jars are not on the classpath. As a result, no classloader can load them. Then getTypesAnnotatedWith return nothing. Please warn it in the readme, and add a method: getTypesNameAnnotatedWith to get the class name instead of class object.

**Comment by ronmamo** [comment]
I'd suggest - read the javadocs, add the relevant classloader, query the store directly when necessary

**Comment by vipcxj** [comment]
I use it in a maven plugin. I add all class path of the denpendcy artifacts, and scan them. So I can't sure the class scaned from which artifact. In fact, I just want to now the class name I care about, I need not the real class object.

**Comment by ronmamo** [comment]
Take a look at https://github.com/ronmamo/reflections-maven for some ideas on how to resolve this. HTH, This is not an issue.
