### ISSUE TITLE
Help with filters and scanners

### ISSUE THREAD

**Issue by eugenio1590** [ronmamo/reflections#177]
I have the following code, and I need to remove the condition of `if(!clazz.isMemberClass())` and perform it in the same search.

````
Reflections reflections = new Reflections(packageName);
Set<Class<?>> factories = reflections.getTypesAnnotatedWith(Factory.class);
if(!factories.isEmpty()){
    for(Class<?> clazz : factories){
        if(!clazz.isMemberClass())  // I need to remove this condition from here
           //Do something
    }
}
````

@ronmamo

**Comment by ronmamo** [comment]
dude, you're missing brackets in the if clause, and spaces before left parenthesis. 
always reformat your code, always check your style.
everything starts from a proper style.
