### ISSUE TITLE
could not get type for name org.eclipse.swt.events.ControlListener from any class loader

### ISSUE THREAD

**Issue by eugenio-caicedo** [ronmamo/reflections#181]
I get the following error:

`org.reflections.ReflectionsException: could not get type for name org.eclipse.swt.events.ControlListener
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.reflections.Reflections.<init>(Reflections.java:168)`

I think is a conflict with the slf4j library versions. When I use only "org.reflections:reflections:0.9.11", this error not showed. But when I include the followings libraries in my project:

`ext.slf4j = '1.7.24'`
`compile "org.slf4j:slf4j-simple:$slf4j"`
`compile "org.slf4j:slf4j-api:$slf4j"`

The error is shown.

**Comment by eugenio-caicedo** [comment]
Please, @ronmamo can you help me with this? Thanks.

**Comment by missley** [comment]
I had got the same warnings too. 
Please, can you help me with this? Thanks.

**Comment by eugenio-caicedo** [comment]
@missley I'm not sure if this can help you. But using Kotlin you have a whole SDK for the reflections. It was the way I could solve. In addition, there is a great documentation. I leave the link: http://kotlinlang.org/docs/reference/reflection.html#reflection
