### ISSUE TITLE
getSubTypesOf returning anonymous types defined in tests

### ISSUE THREAD

**Issue by magrossi** [ronmamo/reflections#188]
My project is organized in the standard way. Production code is stored under `/src/main/java` and test code under `/src/test/java`. When I call `Reflections reflections = new Reflections("my.package");` and subsequently I try to find all classes that implement my interface `MyInterface` by calling `reflections.getSubTypesOf(MyInterface.class)` this is returning anonymous classes that although do implement `MyInterface`, they are on the test side of my code (as tests share the same package name as the classes they are testing).

Is this behavior intended? How do I remove the `/src/test/java` from the search path?

Thank you.

**Comment by xiumeteo** [comment]
Interesting, I reproduce this scenario running your suggested code from a Unit Test. What I found is that the library is using `org.reflections.util.ClasspathHelper#forResource` -> then relying on the `ClassLoader` to load the references to the existing resources ("my.package"). 

Here is the exact code:
``` for (ClassLoader classLoader : loaders) {
            try {
                final Enumeration<URL> urls = classLoader.getResources(resourceName);
                while (urls.hasMoreElements()) {
                    final URL url = urls.nextElement();
```

that `ClassLoader#getResources` returns all the places where the package "my.package" exists, not caring about if its a test or not. I'm thinking about providing the library with a `ClassLoader` could fix your issue, not sure tho, just trying to help.

**Comment by magrossi** [comment]
Hi @xiumeteo , thanks for your input. When running this locally I see that it adds a singular ClassLoader for "file://<my source path>/bin", which is where my binary files get built to. At this point, all files from both /src/main and /src/test are placed in their respective package directories, making it impossible to distinguish them apart from `Test` in the class name of the test classes (as per best practices).

So I'm resigned to using the very `smelly` way of finding all classes that implement my interface but removing the ones that have `Test` on their name.

Thanks again for your input, regards.
