### ISSUE TITLE
Updated from 0.9.10 to 0.9.11 and Reflections doesn't continue past constructor

### ISSUE THREAD

**Issue by Cypherke** [ronmamo/reflections#189]
Got this piece of code that worked fine in 0.9.10:
```java
Reflections reflections = new Reflections("com.myname.myproject");
System.out.println("reflections ok");
Set<Class<? extends MyAbstractClass>> classes = reflections.getSubTypesOf(MyAbstractClass.class);
System.out.println("classes size:" + classes.size());
```
Which gave me this nice output:

> [listenerPool0-thread158] INFO org.reflections.Reflections - Reflections took 154 ms to scan 1 urls, producing 8 keys and 51 values
> reflections ok
> classes size:23

When I try the same with 0.9.11, it just doesn't display any of the verbose output, although it does seem to produce the same number of keys and values:
> [listenerPool0-thread255] INFO org.reflections.Reflections - Reflections took 138 ms to scan 1 urls, producing 8 keys and 51 values

**Comment by xiumeteo** [comment]
I think I´m not following you what is exactly the issue? I see that both lines are the same. Maybe I´m missing something :)

**Comment by Cypherke** [comment]
The 0.9.11 version isn't writing "reflections ok" nor my classes size. The code just doesn't continue after the initial constructor, and no errors are popping up.

**Comment by xiumeteo** [comment]
I just tried to reproduce your issue with a toy project, but couldn't find anything wrong, in fact in my case the I was able to complete the execution of the code you provided. Maybe there is something special about the Abstract class you are using. 

Maybe (this is just a guess from a bug I solved this week) you are using java-8 features in that class and you have an outdated version of javassist. But I´m just guessing. If you can share more details I'll be happy to help.

**Comment by Cypherke** [comment]
Well this sounds promising. My abstract class is pretty basic and doesn't use any java8. But my extending classes do.
So I started checking my outdated components and I upgrade my gradle wrapper from 3.0 to 4.0.2 and behold, it works. Thanks for the hint!
