### ISSUE TITLE
"Could not create Vfs.Dir..." Warnings when building

### ISSUE THREAD

**Issue by Jarota** [ronmamo/reflections#204]
See  [https://github.com/canoo/dolphin-platform/pull/666](url)
Got these warnings when building with `./gradlew clean build`
I've attached a file with the build output.
[buildOutput.txt](https://github.com/ronmamo/reflections/files/1398560/buildOutput.txt)

WARN 23673 --- [ Test worker] org.reflections.Reflections : could not create Vfs.Dir from url. ignoring the exception and continuing

WARN 23673 --- [ Test worker] org.reflections.Reflections : could not create Dir using directory from url file:/home/jammygit/code/dolphin-platform/platform-integration-tests/integration-server/build/resources/test. skipping.

**Comment by ronmamo** [comment]
Thanks, @Jarota.
However, it is preferred to send PR (and not issue), and preferred not attaching a 5mb log... 
I'm closing this, but you're most welcome to contribute.
