### ISSUE TITLE
Reflections.scan allow too many potential result

### ISSUE THREAD

**Issue by rapster** [ronmamo/reflections#205]
I have this jar containing resources like properties, odt, etc. These are contained in "target/classes". Of course, Reflections will scan these files and will throw an exception stating it can't convert properties into a class. Looking a bit more closely to the stacktrace:
```
JavassistAdapter.getOfCreateClassObject(Vfs$File) line: 98	
JavassistAdapter.getOfCreateClassObject(Vfs$File) line: 24	
SubTypesScanner(AbstractScanner).scan(Vfs$File, Object) line: 30	
Reflections.scan(URL) line: 253	
Reflections.scan() line: 202	
Reflections.<init>(Configuration) line: 123	
Reflections.<init>(Object...) line: 168	
Reflections.<init>(String, Scanner...) line: 141	
```
I noticed this condition:

https://github.com/ronmamo/reflections/blob/2f3294c872518464e8c1651d1ca2eeddb2267334/src/main/java/org/reflections/Reflections.java#L248

First, i'm don't know what is the difference between these two methods. Second, acceptsInput return true if the ends with ".class", sound perfect to me, but acceptResult always return true.

So I'm like "there is definitely something's here", no matter what the filter accepts the path or not, acceptResult will bypass it. In simple word, acceptsInput is totally useless...

This new condition has been added by commit https://github.com/ronmamo/reflections/commit/2f3294c.

Before suggesting anything, it would be nice to understand what is the difference between these two methods

**Comment by rapster** [comment]
IMHO, `scanner.acceptResult(fqn)` should be removed from this condition. It ain't the responsability of `Reflections` to do this test but `Scanner`, as if I understand well, the result is determined once className is retrieved: 
```java
    @SuppressWarnings({"unchecked"})
    public void scan(final Object cls) {
		String className = getMetadataAdapter().getClassName(cls);
		String superclass = getMetadataAdapter().getSuperclassName(cls);

        if (acceptResult(superclass)) {
            getStore().put(superclass, className);
        }

		for (String anInterface : (List<String>) getMetadataAdapter().getInterfacesNames(cls)) {
			if (acceptResult(anInterface)) {
                getStore().put(anInterface, className);
            }
        }
    }
```

@ronmamo What do you think?

**Comment by rapster** [comment]
I think the intention was to use `acceptsInput` with fqn like you did previously with `acceptsInput.apply`

**Comment by ronmamo** [comment]
I think you're right, can you send PR?
