### ISSUE TITLE
Reduce conflicting dependencies

### ISSUE THREAD

**Issue by hgschwibbe** [ronmamo/reflections#233]
I tried to include the latest version in our project but we got MethodNotFoundException because we have different guava and gson dependencies set.

Why do this simple java.lang.reflect framework has such heavy weighted dependencies, dependencies you will find in so many projects because they are so common?

That could massively reduce the acceptance of this framework.

**Comment by ljacqu** [comment]
Relates to #194

**Comment by ronmamo** [comment]
guava dependency removed.
fixed in 0.9.12
