### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: javassist/bytecode/ClassFile

### ISSUE THREAD

**Issue by nakshay** [ronmamo/reflections#240]
I get error `Exception in thread "main" java.lang.NoClassDefFoundError: javassist/bytecode/ClassFile
` when using maven dependency, which is using javassist.version 3.21.0-GA, had to add 3.19.0-GA.jar to my eclipse build path to resolve the error.

**Comment by ronmamo** [comment]
fixed in 0.9.12
