### ISSUE TITLE
How scan class in jar?

### ISSUE THREAD

**Issue by user20161119** [ronmamo/reflections#263]
```java
 Reflections reflections = new Reflections(new ConfigurationBuilder()
            .setUrls(ClasspathHelper.forPackage("com.kxwp.common.constants"))
            .setUrls(ClasspathHelper.forPackage("com.yiqing.common.constant"))
            .setUrls(ClasspathHelper.forPackage("com.yiqing.ec.admin.constants"))
            .setUrls(ClasspathHelper.forPackage("com.yiqing.ec.common.constant")).setScanners(new SubTypesScanner(true),
                new TypeAnnotationsScanner(), new FieldAnnotationsScanner(), new MethodAnnotationsScanner(),
                new MethodParameterScanner(), new MethodParameterNamesScanner(), new MemberUsageScanner()));
```
the package `com.yiqing.ec.common.constant` is in a jar file,how can scan the class in the jar file?

**Comment by mhradek** [comment]
You will need to add the jars to the classpath scanner as the defaults aren't set to scan jars. If you know what jars to scan then that will be relatively easy" 

`new URL("jar:file:" + file.getAbsolutePath() + "!/");`

and then add that to Relections via 

`URLClassLoader.newInstance(..`

and then add that classloader to Relfections.
