### ISSUE TITLE
Disable logging to console

### ISSUE THREAD

**Issue by hornta** [ronmamo/reflections#266]
Is there a way to disable logging to console?
```
[org.reflections.Reflections] Reflections took 144 ms to scan 16 urls, producing 35217 keys and 37010 values 
```

**Comment by bharathbattula** [comment]
Are you using slf4j in your project?
If so, try to shut down the logger for that particular package.
I'll do it by simply putting the following line in my logback.xml file

`<logger name="org.reflections" level="OFF"/>`

**Comment by stevenxxiu** [comment]
The above didn't work for me, but this is how I managed to turn it off in code:

```java
// Disable logging of `Reflections`, which is very verbose
ch.qos.logback.classic.Logger root;
root = (ch.qos.logback.classic.Logger) LoggerFactory.getLogger("org.reflections");
root.setLevel(ch.qos.logback.classic.Level.OFF);
```
