### ISSUE TITLE
annotations returned by Method getMethodsAnnotatedWith() is a proxy object

### ISSUE THREAD

**Issue by nutharsh** [ronmamo/reflections#267]
I am using reflections library (0.9.11) to scan for methods with certain annotations in a gradle plugin development.

Sample Config:
`
ConfigurationBuilder configurationBuilder = new ConfigurationBuilder();
        configurationBuilder.addClassLoader(urlClassLoader);
        configurationBuilder.addUrls(urls);
        final FilterBuilder filterBuilder = new FilterBuilder();
        configurationBuilder.filterInputsBy(filterBuilder.includePackage(scanPackagesSet.toArray(new String[scanPackagesSet.size()])));
        configurationBuilder.addScanners(new MethodAnnotationsScanner());
        configurationBuilder.setExpandSuperTypes(false);
`
Sample Usage:
`
final Set<Method> methods = reflections.getMethodsAnnotatedWith(GET.class);
Arrays.stream(mtd.getDeclaredAnnotations()).forEach(
                    annotation -> {
System.out.println(annotation.getClass());
});
`
Result:
`class com.sun.proxy.$Proxy176`

Is this because of classloading issue? Config issue? Or Actual issue with library?

**Comment by nutharsh** [comment]
This might be permission issue or lib issue.

Sample Code
`
LOG.info("annotationSet={} annotationBeingChecked={} isPresent?{}", annotationSet, ApiOperation.class, mtd.isAnnotationPresent(ApiOperation.class));

`


Sample Output
`
annotationSet=[io.swagger.annotations.ApiOperation,org.springframework.web.bind.annotation.PostMapping]
annotationBeingChecked=interface io.swagger.annotations.ApiOperation
isPresent?false
`

**Comment by nutharsh** [comment]
**Additional Info:** .class files are generated from Kotlin source code.

**Comment by ljacqu** [comment]
Use annotationType() instead of getClass() – https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/Annotation.html#annotationType--

This is normal Java behavior
