### ISSUE TITLE
TypeAnnotationsScanner only sees nested classes

### ISSUE THREAD

**Issue by Farmbuyer** [ronmamo/reflections#268]
So as a test to see if Reflections will work for us, I made an annotation of the simplest kind:

    @Retention(RetentionPolicy.RUNTIME)
    public @interface TestAnnotation
    {
        public String value();
    }

and used it in one of our existing classes, plus a quick added nested class:

    @TestAnnotation("foo foo foo")
    public class ActualFunctionalityClass
    {
        @TestAnnotation("bar bar bar")
        class Thing {}

        .......
    }

All of that gets built into a JAR on the local filesystem.  Now I'm trying to use Reflections 0.9.9-RC1 to examine that JAR file:

    Path jar_file = ... code elsewhere that sets absolute pathname ...;
    
    
    // This works:
    URL url = jar_file.toUri().toURL();
    // so does this:
    //URL url = new URL("jar:file:" + jar_file.toString() + "!/");
    
    Reflections r = new ConfigurationBuilder()
        //.addClassLoader(URLClassLoader.newInstance(new URL[]{url}))
        .setUrls(url)
        .setScanners(
            new FieldAnnotationsScanner(),
            new SubTypesScanner(false),
            new TypeAnnotationsScanner(),
            new TypeElementsScanner()
            )
        .build();

    Multimap<String,String> mmap = r.getStore().get(TypeAnnotationsScanner.class);
    for (String key : mmap.keySet()) {
        System.err.format("key %s:%n", key);
        for (String value : mmap.get(key)) {
            System.err.format("   -> %s%n", value);
        }
    }

(The `setUrls()` call seems to be sufficient to get the JAR scanned; adding the classloader to look at the JAR that way doesn't make a difference as far as I can tell.  If I'm missing something crucial please let me know.)

So I got a dump of lots of expected things like

    key java.lang.FunctionalInterface:
        -> ourproject.SomeClass$SomeInterfaceTaggedAsFunctional
        -> ourproject.OtherClass$SomeOtherInterfaceTaggedAsFunctional

as well as

    key java.lang.annotation.Retention:
        -> ourproject.TestAnnotation
    key ourproject.TestAnnotation:
        -> ourproject.ActualFunctionalityClass$Thing

But I also expected to see TestAnnotation mapping to ActualFunctionalityClass itself, in addition to the nested Thing class.

Is there something I'm missing here as to how the annotations are mapped?

(Eventually I'm going to be doing the scanning via `getTypesAnnotatedWith` rather than trawling through the store, but I wanted to try some simple cases first.)

**Comment by ronmamo** [comment]
as tested, this should work and return both upper and internal classes. please use latest version. provide a reproducible test/jar if issue still happens.
