### ISSUE TITLE
No classes found with specified annotation in specified package.

### ISSUE THREAD

**Issue by MairwunNx** [ronmamo/reflections#286]
#### Code: (domain value is `com.mairwunnx`)

![image](https://user-images.githubusercontent.com/39625750/77640362-4c451100-6f6b-11ea-823e-ef473c410dec.png)

`getTypesAnnotatedWith` return empty collection and for each not iterate on elements because `getTypesAnnotatedWith` returned empty collection.

In bundle jar exist all packages and classes. I also tried use ClasspathHelper.forPackage() but it not throw exception consequently package exist.

##### OS \ JDK: Windows 10 \ JDK 1.8

**Comment by MairwunNx** [comment]
I also tried to reproduce this problem on pure kotlin gradle project.

### ¯\_(ツ)_/¯ What happens?

Orange arrows - classes (for kotlin it object but like class with instance).
Green arrow - annotation class.
Red - what actually i get. 

![image](https://user-images.githubusercontent.com/39625750/77664107-ea969e00-6f8e-11ea-82e6-263b2ee6ecfe.png)

**Comment by MairwunNx** [comment]
Hmm. With configuration builder i get my classes (it with pure kotlin gradle project).

Code:

![image](https://user-images.githubusercontent.com/39625750/77665441-b91ed200-6f90-11ea-9e08-f6e0fe6eff2b.png)

Result:

`[com.test.sasda.v1.ClassOne, com.test.sasda.ClassTwo]`

**Comment by MairwunNx** [comment]
But when i use this code with forge i get zero classes. My jar mod loading by forge, maybe it means something.

**Comment by ronmamo** [comment]
thanks @MairwunNx , it is preferred to use `ConfigurationBuilder` for instantiating Reflections, and get the right urls.

you've mentioned above *Reflections used with minecraft forge (mod loader for Minecraft game)* - damn that sounds interesting... maybe you can drop a line or two 'bout it?
