### ISSUE TITLE
License issue with GPL in Checker Qual

### ISSUE THREAD

**Issue by MichaelHornung** [ronmamo/reflections#287]
Hi,

we are using reflections as a deep dependeny in our microservices. There are issues in our foss compliance tool FOSSA after scanning.
![image](https://user-images.githubusercontent.com/53259450/78010689-f691af80-7342-11ea-97dc-f16d6773ea59.png)
![image](https://user-images.githubusercontent.com/53259450/78010707-fc879080-7342-11ea-9e74-24d7462b2723.png)

Checker Qual Framework includes a copy left and therefore i think also reflections has this copy left effect.
Here is the license of Checker Qual: https://github.com/typetools/checker-framework/blob/master/LICENSE.txt
Why can you license reflections under a permissive license although there are dependencies with copy left included?

Thankx!
Michael

**Comment by haumacher** [comment]
The referenced license reads as:

> ...
> A few parts of the Checker Framework have more permissive licenses.
> 
>  * The annotations are licensed under the MIT License.  (The text of this
>    license also appears below.)  More specifically, all the parts of the
>    Checker Framework that you might want to include with your own program
>    use the MIT License.  This is the checker-qual*.jar and
>    checker-compat-qual*.jar files and all the files that appear in them:
>    every file in a qual/ directory, plus utility files such as
>    NullnessUtil.java, RegexUtil.java, SignednessUtil.java, etc.  In
>    addition, the cleanroom implementations of third-party annotations,
>    which the Checker Framework recognizes as aliases for its own
>    annotations, are licensed under the MIT License.
> ...

Isn't it just these libraries that your compliance tool complains about? These are licensed under MIT License and are not a problem?

**Comment by MichaelHornung** [comment]
@haumacher Yes that is the solution of our issue.
