### ISSUE TITLE
When prefix of Reflections is blank string, cannot find subTypes in whole classpath scope.

### ISSUE THREAD

**Issue by l4wei** [ronmamo/reflections#315]
Version: 0.9.12.
Problem code: Reflections reflections = new Reflections("");
Description: Must package the program be a jar, this problem will be happened.

**Comment by Kaktushose** [comment]
Okay, so for anyone also having this issue, I've found a solution. 

```java
new Reflections(new ConfigurationBuilder()
    .setScanners() // the scanners you need
    .setUrls(ClasspathHelper.forClass(getClass()))
);
```

**Comment by ronmamo** [comment]
thanks @l4wei and @Kaktushose , it is preferred to use `ConfigurationBuilder` so that urls are correctly resolved from classpath. I've updated the docs and will update further.
