### ISSUE TITLE
how I can get classes that implements a specific type (interface)

### ISSUE THREAD

**Issue by Ahmed-Abdelhak** [ronmamo/reflections#316]
hi

I have a small question, how I get all the data classes (in kotlin) that implements a specific interface ?

Thanks in advance

**Comment by InYourHead** [comment]
In Java you can make:

`Reflections reflections = new Reflections("com.your.package");
    Set<Class<? extends IYourInterface>> classes = reflections.getSubTypesOf(IYourInterface.class);`
    
    You should be able to make it in similar way using kotlin.
