### ISSUE TITLE
Unable to find classes present under src/test/java from src/main/java

### ISSUE THREAD

**Issue by kunalashar25** [ronmamo/reflections#318]
Hi,

I want to find all the classes that are present under `src/test/java`
**Package Structure:**
```
src/test/java
 - com.ref.test
  -- LoginTest.java
  -- SearchTest.java
```

I'm writing the below method in the class **Execute.java** which is present under `src/main/java`
**Package Structure:**
```
src/main/java
 - com.ref.page
  -- Execute.java
```

```
private static Reflections getAllTestcaseClass() {

        final ConfigurationBuilder config = new ConfigurationBuilder()
                .setScanners(new ResourcesScanner(), new SubTypesScanner(false))
                .setUrls(ClasspathHelper.forPackage(testcasePackagePath))
                .filterInputsBy(new FilterBuilder().includePackage(testcasePackagePath));

        final Reflections reflect = new Reflections(config);
        return reflect;
    }
```
`testcasePackagePath = "com.ref.test"`

If I keep the `Execute.java` class under `src/test/java` then it can locate LoginTest and SearchTest classes but when I try to do the same from `src/main/java` then it is not able to find it.

**Comment by kuFEAR** [comment]
Hi, you can add this classpath to unit tests via gradle
```groovy
sourceSets {
    test {
        java.srcDirs = ["src/main/java", "src/test/java"]
    }
}
```
