### ISSUE TITLE
reflections.getResources: match full path, not simple name

### ISSUE THREAD

**Issue by avodonosov** [ronmamo/reflections#322]
Why is the regex passed to `reflections.getResources(pattern)` only matched against simple name?

It's is unnecessary limiting, in my case I can not distinguish resrouces by simple name, full path matters.

I don't see a way to do so (note, I can not express the path condition as simple `prefix` constant, that must be a regex)

**Comment by avodonosov** [comment]
```java
        Pattern resourcePattern = Pattern.compile("my_root_package/.*/.*\\.txt");
        Reflections reflections = new Reflections(
                new ConfigurationBuilder()
                        .setUrls(ClasspathHelper.forPackage("my_root_package"))
                        .filterInputsBy(input -> resourcePattern.matcher(input).matches())
                        .setScanners(new ResourcesScanner()));

        for (String path : reflections.getResources(name -> true)) {
            // work with the resource
        }

```

**Comment by sschuberth** [comment]
For reference, this seems to duplicate https://github.com/ronmamo/reflections/issues/148.
