### ISSUE TITLE
inconsistent behavior from getSubTypesOf for Scala classes

### ISSUE THREAD

**Issue by jimka2001** [ronmamo/reflections#324]
I'm trying to use the reflections library from within Scala.
When I ask for the subclasses of `List[Any]` I don't find any.  However, when I asked on a scala help group, [Help with org.reflections api](https://users.scala-lang.org/t/help-with-org-reflections-api/7464/2), someone else tried my code and correctly found the expected subclasses.

Here is the scala code I'm using
```scala
object sanityCheck {
  val refl = new org.reflections.Reflections("")

  def main(argv:Array[String]):Unit = {
    describeSubclasses(classOf[java.lang.Number])
    makeNumber()
    describeSubclasses(classOf[List[Any]])

  }
  def describeSubclasses(cl:Class[_]):Unit = {
    import java.lang.reflect.Modifier
    // getSubTypesOf does not realize that a type is a subtype of itself
    val subs:List[Class[_]] = cl :: refl.getSubTypesOf(cl).toArray.toList.collect {
      case c: Class[_] => c
    }
    println("---------")
    for{ sub <- subs
         } println( s"$sub is " + Modifier.toString(sub.getModifiers))

  }
  def makeNumber():Unit = {
    class MyNumber extends Number {
      def doubleValue():Double = 0.0
      def longValue():Long = 0
      def intValue():Int = 0
      def floatValue():Float = 0.0F
    }
    new MyNumber
  }
}
```

And here is the printed output I see
```
---------
class java.lang.Number is public abstract
class genus.sanityCheck$MyNumber$1 is public
---------
class scala.collection.immutable.List is public abstract
```

Another user ran my code and sees the following, correct, output.
```
---------
class java.lang.Number is public abstract
class genus.sanityCheck$MyNumber$1 is public
---------
class scala.collection.immutable.List is public abstract
class scala.collection.immutable.$colon$colon is public final
class scala.collection.immutable.Nil$ is public final
```

I am using version 0.9.12 of the reflections library.

**Comment by jimka2001** [comment]
I've done some additional experimentation.   Here are several pieces of information I hope the developers find useful useful.

- Calling the constructor with `""` as argument gives inconsistent behavior. `org.reflections.Reflections("")`.    It seems to be *accepted* as a valid argument.

- Using reflections version 0.9.12 I very often get the following error, reverting to 0.9.11 avoids the error.

```
Scanner SubTypesScanner was not configured
org.reflections.ReflectionsException: Scanner SubTypesScanner was not configured
	at org.reflections.Store.get(Store.java:39)
	at org.reflections.Store.get(Store.java:61)
	at org.reflections.Store.get(Store.java:46)
	at org.reflections.Store.getAll(Store.java:93)
	at org.reflections.Reflections.getSubTypesOf(Reflections.java:404)
```

- Sometimes, given two classes, `c1` and `c2`, I can verify that `c2` is a superclass of `c1`, however, `getSubTypesOf` says that `c2` has no subtypes.  The test was made as follows, which verifies that `List[Any]` has at least two subclasses, the empty list, and the non-empty list.  The two assertions shown here pass or fail depending on which java version I use.
```scala
test("reflect.getSubTypesOf"){
    val reflect = new org.reflections.Reflections()
    assert(reflect.getSubTypesOf(classOf[List[Any]]).toArray.contains(List(1,2,3).getClass))
    assert(reflect.getSubTypesOf(classOf[List[Any]]).toArray.contains(List.empty.getClass))
  }
```

- Depending on which java executable I use, I get very different behavior from the `getSubTypesOf` method.    
-- java version 1.8.0_242 seems to behave correctly
```
/Library/Java/JavaVirtualMachines/openjdk8/Contents/Home/bin/java -version
/Library/Java/JavaVirtualMachines/openjdk8/Contents/Home/bin/java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```
-- java version 11.02 fails
```
/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java -version
/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```
-- particularly the java built in to my installation of IntelliJ fails
```
"/Applications/IntelliJ IDEA CE.app/Contents/jbr/Contents/Home/bin/java" -version
"/Applications/IntelliJ IDEA CE.app/Contents/jbr/Contents/Home/bin/java" -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment JBR-11.0.10.9-1341.41-dcevm (build 11.0.10+9-b1341.41)
Dynamic Code Evolution 64-Bit Server VM JBR-11.0.10.9-1341.41-dcevm (build 11.0.10+9-b1341.41, mixed mode)
```

**Comment by ronmamo** [comment]
thanks @jimka2001 

instantiating with `""` is discouraged and might result in different urls resolved from the classpath. using `ConfigurationBuilder` explicitly is preferred. 

scanner was not configured exception - this is known issue on 0.9.12, a simple workaround is to check if the store contains scanned values for the scanner before query. next version fixes this.

also matrix testing are planned to be added, if you want to contribute that'd be great

**Comment by jimka2001** [comment]
Sorry I don't know anything about matrix testing.   is that something I can do from Scala?

**Comment by jimka2001** [comment]
@ronmamo, can you comment a bit more about what I need to do as a Scala programmer.  I tried what you recommended (at least as best I can understand what you recommended).

```scala
import org.reflections.util.ConfigurationBuilder

val reflect = new org.reflections.Reflections(ConfigurationBuilder)
```
But this gives a compilation error.
```
/Users/jnewton/Repos/regular-type-expression/cl-robdd-scala/src/main/scala/genus/SAtomic.scala:317:49
class org.reflections.util.ConfigurationBuilder is not a value
  val reflect = new org.reflections.Reflections(ConfigurationBuilder)
```

**Comment by potatoxf** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件

**Comment by mitkurale** [comment]
@ronmamo  I am getting the same error and we are using reflections version '0.9.11'. What is the next good version which fixes this issue?
Caused by: org.reflections.ReflectionsException: Scanner SubTypesScanner was not configured
        at org.reflections.Store.get(Store.java:39)
        at org.reflections.Store.getAllIncluding(Store.java:75)
