### ISSUE TITLE
Callback that reports detected annotation during scan

### ISSUE THREAD

**Issue by gdrouet** [ronmamo/reflections#34]
Currently the API collects the annotated elements and returns them in a collection. An efficient approach would be to call a callback each time an annotation is detected:

```java
reflections.getTypesAnnotatedWith(
        javax.inject.Singleton.class,
        (Class<?> c) -> System.out.println(c.getName()));
```

What do you think?

**Comment by ronmamo** [comment]
Sorry for just responding. Although it looks more 'reactive' it has no practical effect in the case of subtypes, which are transitive by nature and are computed a posteriori.
