### ISSUE TITLE
Migrating from 0.9.10 to 0.10.2, forPackage does not honor full package name as filter?

### ISSUE THREAD

**Issue by hjohn** [ronmamo/reflections#365]
If I do this:

    ConfigurationBuilder builder = new ConfigurationBuilder()
      .forPackages(packageNamePrefixes)
      .setScanners(
        Scanners.TypesAnnotated,
        Scanners.FieldsAnnotated,
        Scanners.MethodsAnnotated
      );

Internally, it seems to convert the package names to URL's, and in the process loses crucial information about the package I'm interested in scanning. 

If I only want to scan a subset of packages (let's say `hs.ddif.plugins.test.project`) version 0.10.2 will now also find types in `hs.ddif.plugins`.  Version 0.9.10 doesn't do this -- it correctly filters by the package given.

Is this intended?  What's the new way of achieving a package filter?

**Comment by ronmamo** [comment]
yes, `forPackage` is just a shortcut to `addUrls(ClasspathHelper.forPackage())` but without the input filter.
would you suggest to change that? also raise in #304

**Comment by hjohn** [comment]
It is just a bit confusing, perhaps document this explicitely that it is only using the package name to discover the URL/JAR involved, not actually filtering by it.  A name like `discoverURLsForPackages` might have been clearer.

I've solved it now by adding an explicit filter:

    Pattern filterPattern = Pattern.compile(
      Arrays.stream(packageNamePrefixes)
        .map(pnp -> pnp.replace(".", "/"))
        .collect(Collectors.joining("|", "(", ").*?"))
    );

    Configuration configuration = new ConfigurationBuilder()
      .forPackages(packageNamePrefixes)
      .filterInputsBy(s -> filterPattern.matcher(s).matches());

**Comment by hjohn** [comment]
Thank you thought for releasing 0.10.2 -- I finally managed to upgrade from 0.9.10 and get rid of the guava dependency :)

**Comment by ronmamo** [comment]
thanks @hjohn , I guess you're right about forPackage.
btw, nice library! [hs.ddif](https://github.com/hjohn/hs.ddif)

```
// ComponentScanner#findComponentTypes
reflections.get(
    TypesAnnotated.with(Named.class, Singleton.class, WeakSingleton.class, Producer.class, PluginScoped.class)
        .add(FieldsAnnotated.with(Inject.class)
            .add(ConstructorsAnnotated.with(Inject.class))
            .add(MethodsAnnotated.with(Inject.class, Produces.class))
            .map(name -> {
                String s = name.substring(0, name.lastIndexOf('('));
                return s.substring(0, name.lastIndexOf('.'));
            }))
        .asClass(classLoader)
        .filter(withClassModifier(ABSTRACT).negate()));
```

**Comment by hjohn** [comment]
Thanks for that suggestion, integrated with some minor changes: https://github.com/hjohn/hs.ddif/commit/6495453c8d726b26b8e063fa11fd582d5d598958
