### ISSUE TITLE
Add osgi version of jar

### ISSUE THREAD

**Issue by larubbio** [ronmamo/reflections#40]
Currently for our project we are creating an wrapper jar that allows us to make use of this project within our OSGi enabled project.  

https://github.com/motech/external-osgi-bundles/tree/master/reflections

Adding the manifest to the source project would enable us to make use of new releases faster.

**Comment by ronmamo** [comment]
care to PR?

**Comment by ge0ffrey** [comment]
It should be a matter of adding these 2 code blocks in your pom:

       <packaging>bundle</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>2.3.7</version>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Import-Package>
                            org.jboss.vfs.*;resolution:=optional,
                            *
                        </Import-Package>
                        <Export-Package>
                            org.reflections.*
                        </Export-Package>
                        <Bundle-SymbolicName>org.reflections</Bundle-SymbolicName>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>

**Comment by larubbio** [comment]
I created a pull request for this #66

**Comment by meshuga** [comment]
+1

**Comment by mattbishop** [comment]
+1

**Comment by ge0ffrey** [comment]
+1

**Comment by ctron** [comment]
+1

**Comment by ctron** [comment]
Is this fixed now?

**Comment by glefloch** [comment]
Hi, I would to contribute on this project, will this issue be a good start for a pull request?

**Comment by ronmamo** [comment]
@ctron Yes, It should be fixed now. Can you double check it?

**Comment by ronmamo** [comment]
@glefloch Yes please! Just fork and make a PR

**Comment by ctron** [comment]
Looks good to me. Only version import for guava could be changed a bit. Guava doesn't follow OSGi semantic versioning, so currently it is only possible to use your library with one exact version of guava. However probably later versions of guava would also work, so for guava I would suggest to remove the upper version bound.

**Comment by glefloch** [comment]
I just started looking at the projects, the build of the osgi bundle works using the `build` profile. 
The generated `MANIFEST.MF` seems correct. Is it ok for you?
