### ISSUE TITLE
SLF4J Implementation seemes Brocken

### ISSUE THREAD

**Issue by snoweuph** [ronmamo/reflections#405]
Im running Version 0.10.2 of this Package with Gradle 7.4

when using getSubTypesOf I get A Message in the COnsole Saying:

```bash
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

what should I do? I myself dont use SLF4J and this Message only pops up when using this Lib

**Comment by Sylordis** [comment]
Reflections is using SLF4J for it's logging system. You can add SLF4J in your dependencies but then it'll transform the messages into this issue:
https://github.com/ronmamo/reflections/issues/386
