### ISSUE TITLE
javassist is not optional but has a case?

### ISSUE THREAD

**Issue by vafada** [ronmamo/reflections#41]
https://github.com/ronmamo/reflections/blob/master/pom.xml#L68-L73

```
 <dependency>
<groupId>org.javassist</groupId>
<artifactId>javassist</artifactId>
<version>${javassist.version}</version>
<optional>false</optional> <!-- case: when not actually scanning with javassist or if using {@link Reflections.collect()} -->
</dependency>
```

This says that ```javassist``` is a required dependency, but the comment says that you can scan components without using ```javassist```.

**Comment by ronmamo** [comment]
Sorry for the late response - Javassist is effectively needed for scanning, and can be excluded in case you're using Reflections.collect (+1) or using another MetadataAdapter (-1)
Keep up the good work on querydsl ;)
