### ISSUE TITLE
All classes in a package and combine several filters

### ISSUE THREAD

**Issue by doctore** [ronmamo/reflections#42]
First of all, congratulations for your work. 

I do not know if it is the right place for this question and if it is really a feature that is not developed.
If I write, for example, three different classes:

package controllers;
public class A {}

package controllers;
public class B extends A {}

package controllers;
@MyAnnotation
public class C extends A {}

1. How could I get all the classes in a given package (controllers in this case)?  getAllTypes() returns a Set[String] but not an Set[Class[?]]

2. How I can combine multiple filters at once?
new Reflections("controllers").getSubTypesOf(A.class).getTypesAnnotatedWith(MyAnnotation.class);

Thanks in advance.

**Comment by ronmamo** [comment]
The short answer for 1 is to call Class.forName for each (or ReflectionUtils.forNames). The longer answer is that getting all types is a bad practice. The better practice would be to add meaningful metadata on your classes (such as annotations or interfaces), and then ask questions about your model using that meta-model.
As for 2 - you can't, just intersect the two results.

BTW, it is better to ask such questions in https://groups.google.com/forum/#!forum/google-code-reflections (I'll add it to the README...)
Good luck
