### ISSUE TITLE
getTypesAnnotatedWith with false default for "honorInherited"

### ISSUE THREAD

**Issue by nauni1977** [ronmamo/reflections#45]
Hello,

first of all thanks for this very useful library! If I understand the documentation at 

http://reflections.googlecode.com/svn/trunk/reflections/javadoc/apidocs/index.html?org/reflections/Reflections.html

correct - the behavior between 0.9.8 and 0.9.9 should be the same while calling the method "getTypesAnnotatedWith(SomeAnnotation.class)". I think this should be redirected to: "getTypesAnnotatedWith(SomeAnnotation.class, true)" - like documentation describes. But it is redirected to "getTypesAnnotatedWith(SomeAnnoation.class, false)".

Since 0.9.9 all SubTypes of "really" annotated class/ interface are returned, at 0.9.8 only the "really" annotated class/ interface was returned - not the implementing or extending classes of this interface containing the annotation.

If I'm right it would be great if you can fix this little error.

Best regards

Oli

**Comment by ronmamo** [comment]
True, Reflections since 0.9.9 changed and it is not honoring Inherited by default. I didn't like it in the first place... 
Thanks Oli for your comment.
