### ISSUE TITLE
Version release of 0.10.3 planned?

### ISSUE THREAD

**Issue by Lonzak** [ronmamo/reflections#453]
I just wanted to carefully ask when the next version release is planned?
A rough time frame would suffice...  I hope that the following sentence of [#411](https://github.com/ronmamo/reflections/issues/411) is not true:

> [...] the Reflections library as it seems, is not proactively maintained.

We are eagerly awaiting the fix for the following issue, which blocks us from using a newer (patch) version of java.

[#395](https://github.com/ronmamo/reflections/issues/395),[ #440](https://github.com/ronmamo/reflections/issues/440) , [#427](https://github.com/ronmamo/reflections/issues/427)

**Comment by Lonzak** [comment]
Anything?

**Comment by heruan** [comment]
Is this project really dead?

**Comment by Lonzak** [comment]
Last release from 2021. Last issue from last year. No answer here....One could think so.

**Comment by Bruce0203** [comment]
I guess this bug related from JVM... 
org.objectweb.asm occurred exception in same environment situation

**Comment by ronmamo** [comment]
0.10.3 is planned but delayed due to lack of time. sorry for the inconvenience and please consider assisting in polishing branch ref-0.10.3.

**Comment by Lonzak** [comment]
@ronmamo What kind of polishing is needed?

**Comment by Lonzak** [comment]
@ronmamo What kind of polishing is needed?

**Comment by Lonzak** [comment]
@ronmamo What kind of polishing is needed?
