### ISSUE TITLE
What polishing is necessary for release of 0.10.3?

### ISSUE THREAD

**Issue by Lonzak** [ronmamo/reflections#458]
> 0.10.3 is planned but delayed due to lack of time. sorry for the inconvenience and please consider assisting in polishing branch ref-0.10.3.

@ronmamo Since you didn't reply in the [(already closed) issue](https://github.com/ronmamo/reflections/issues/453):

**What kind of polishing is needed?**

The bugs ([#395](https://github.com/ronmamo/reflections/issues/395),[ #440](https://github.com/ronmamo/reflections/issues/440) , [#427](https://github.com/ronmamo/reflections/issues/427)) are really problematic - so maybe the community can step in and help releasing...

**Comment by HenningL** [comment]
the classloader param #445  would be good and should be easy to fix

**Comment by Lonzak** [comment]
I yesterday forked the project and tried the suggested bugfix for issues (#395, #440, #427) However it did not help the error still occurs. Thus I completely removed the reflection lib and replaced the functionality with something else...
