### ISSUE TITLE
Non-Recursive Scanning Not Supported or Documented

### ISSUE THREAD

**Issue by saden1** [ronmamo/reflections#62]
This might be more of a question than an issue. I have a package I want to scan for classes (i.e. package "a.b.c" ) but I am not interested in the classes of its sub packages (i.e. package "a.b.c.d"). How do get a hold of only classes in package "a.b.c"?

**Comment by saden1** [comment]
I suppose I could use regex to exclude sub-package classes/content. Ideally, one should be able to disable the recursive nature of Reflections using the configuration builder.

**Comment by ronmamo** [comment]
You're right, using a filter would do the work (filterInputsBy), still, classpath scanning is recursive by nature.
