### ISSUE TITLE
ConfigurationBuilder.build() violates the principle of least surprise

### ISSUE THREAD

**Issue by ieure** [ronmamo/reflections#63]
I tried to use `ConfigurationBuilder` to add `MethodAnnotationsScanner` to my `Reflections` instance, but encountered some behavior that violates my principle of least surprise.

Here's what I wrote:

```java
    return new Reflections(new ConfigurationBuilder()
                           .setScanners(new MethodAnnotationsScanner(),
                                        new SubTypesScanner(),
                                        new TypeAnnotationsScanner())
                           .build());
```

I was very annoyed to find that I was still unable to call `getMethodsAnnotatedWith()` on this `Reflections` instance. After digging through the code, I discovered that `ConfigurationBuilder` is a nonstandard application of the builder pattern. Rather than encapsulating mutable state and producing an immutable `Configuration` when you call `.build()`, the `ConfigurationBuilder` *is itself the configuration*, and `Configuration` is just an interface. Calling a static method on an instance of a class invokes the static method, which returns a default configuration even though the code superficially appears to create a custom one.

Recommendations:
 - Eliminate the `Configuration` interface.
 - Rename `ConfigurationBuilder` to `Configuration`.
 - (Optional) Make `Configuration` immutable, add a new `ConfigurationBuilder` which encapsulates the mutability and produces a `Configuration` when `.build()` is called.

**Comment by ronmamo** [comment]
Well, calling a static method (build) on an instance object (ConfigurationBuilder) violated the principle of least surprise. And using a proper IDE (intellij) or any code style tool (whatever) - you'll get a warning you can't refuse. Annoys me too, but hey, it's Java.

**Comment by ieure** [comment]
The behavior of calling static methods on object instances is well known, the surprise is that **`ConfigurationBuilder.build()` is static**. This is atypical for a Builder.

 - Guava's [ImmutableMap.build()](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/ImmutableMap.Builder.html#build()) is a non-static method which returns an instance of the thing being built.
 - Apache HttpClient [uses](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/methods/RequestBuilder.html#build()) [this](https://github.com/apache/httpclient/blob/trunk/httpclient/src/main/java/org/apache/http/client/utils/URIBuilder.java#L119) [pattern](https://github.com/apache/httpclient/blob/trunk/httpclient/src/main/java/org/apache/http/impl/client/HttpClientBuilder.java) [everywhere](https://github.com/apache/httpclient/blob/trunk/httpclient/src/main/java/org/apache/http/client/entity/EntityBuilder.java#L313).
 - Jersey [does the same](https://jersey.java.net/apidocs/latest/jersey/javax/ws/rs/core/Response.ResponseBuilder.html#build())
 - Your code [runs counter](http://en.wikipedia.org/wiki/Builder_pattern#Structure) [to most examples](http://www.javaworld.com/article/2074938/core-java/too-many-parameters-in-java-methods-part-3-builder-pattern.html) [of builders](http://www.javacodegeeks.com/2013/01/the-builder-pattern-in-practice.html)

What you have is much closer to a factory than a builder. Renaming it to reflect this would also be fine. I'd be happy to submit a patch doing either this or my original recommendations.
