### ISSUE TITLE
Reflections with Jacoco

### ISSUE THREAD

**Issue by poznachowski** [ronmamo/reflections#64]
Hi,
I have a project where I'm using Reflections and I want to use Jacoco for coverage (as it's Java 8 project). However, when I run tests with Jacoco agent in place, tests start to fail. I found in Jacoco FAQ:

> My code uses reflection. Why does it fail when I execute it with JaCoCo?
> 
> To collect execution data JaCoCo instruments the classes under test which adds two members to the classes: A private static field $jacocoData and a private static method $jacocoInit(). Both members are marked as synthetic.
> 
> Please change your code to ignore synthetic members. This is a good practice anyways as also the Java compiler creates synthetic members in certain situation. 

Is it something you guys do in your code ? Or do you think it may not be the cause ?

**Comment by ronmamo** [comment]
It might be the cause, or the Java 8 part... Any meaningful exception caught?

**Comment by ronmamo** [comment]
not reproducible with java 8, gradle and jacoco plugin. need more info. 
make sure you're using the latest Reflections version, that uses Javassist >= 3.18.2-GA
