### ISSUE TITLE
reflections-spring discontinued?

### ISSUE THREAD

**Issue by RenanSFreitas** [ronmamo/reflections#67]
There is a page* in Reflections wiki that suggests a reflections-spring project... I can't find it's repository. Was this project discontinued for some reason?

I'm asking because during an experiment related to Spring application context loading time, I tried to use reflections-spring and ended up fixing some things in it and adding others as I needed. Now I think it could be useful for others to have the fixes I did (maybe).

* https://code.google.com/p/reflections/wiki/ReflectionsSpring

**Comment by ronm-logz** [comment]
@RenanSFreitas, 
except for the code already committed into the old google code repo (soon to be closed), there is no repository elsewhere.
I think it'll be great if you create a repo for that, and use the existing code, if you'd like. I'm happy to share :)
Let me know, and you can contact me at ronmamo at g m ail
