### ISSUE TITLE
Release 0.9.10 or 0.10? 

### ISSUE THREAD

**Issue by ifesdjeen** [ronmamo/reflections#68]
Hi, it's been quite some time since the last release (Sep 25, 2014), and there are some great improvements since then, could you cut a new release? I'm not sure which version it could / should be. 

Would be great.

Thanks a ton!

**Comment by pavlobaron** [comment]
+1

**Comment by toddwest** [comment]
+1

**Comment by ronmamo** [comment]
0.9.10 released. your kind feedback is required.

**Comment by ifesdjeen** [comment]
:+1: w0000t! Thanks a lot! I've already upgraded, if there's any problem arising, I'll report it asap.

**Comment by ronmamo** [comment]
Alex, you're the man!

**Comment by natros** [comment]
Cool. Waiting for it on maven central.
