### ISSUE TITLE
What am I doing wrong ? 

### ISSUE THREAD

**Issue by oskaremil** [ronmamo/reflections#78]
Using 0.9.10 I have followed the tutorials but I am not able to load any subtypes of any class.

Given this class:

```java
package com.oeskeide.fairplaysquad.storage.helper;

import com.oeskeide.fairplaysquad.storage.SQLiteTable;
import com.oeskeide.fairplaysquad.storage.model.Squad;

/**
 * Created by oes on 04/07/15.
 */
public class SquadHelper extends SQLiteTable{
    @Override
    public String getCreateTableStatement() {
        StringBuilder sb = new StringBuilder(String.format("create table %s0 ", Squad.TABLE_NAME));
        sb.append(String.format("(%s0 %s1, %2 %3)",
                Squad._ID, "integer primary key",
                Squad.COLUMN_NAME, "text"));
        return sb.toString();

    }
}

```

and another class declared in a similar way I am trying to load them all with reflections:

```java
@Override
    public void onCreate(SQLiteDatabase db) {
        Reflections r = new Reflections("com.oeskeide.fairplaysquad.storage.helper");
        Set<Class<? extends SQLiteTable>> tableHelpers = r.getSubTypesOf(SQLiteTable.class);


    }
```

tableHelpers is an empty set. Even if I use `r.getAllTypes()` I should at least expect to find the type names or similar of all the classes in that package but that set is empty too.

First I wanted SQLiteTable to be a generic interface, `SQLiteTable<T>`, then I swapped it to an interface defined as `SQLiteTable`. My last attempt was to make it an abstract class but that does not work either.

**Comment by martin-g** [comment]
Please use https://groups.google.com/forum/#!forum/google-code-reflections or StackOverflow for help.
The issue tracker is for bug reports.

It could be that the current context class loader at `#onCreate()` doesn't see your classes. It is hard to say what happens without a test case that reproduces the problem.

**Comment by hartmut27** [comment]
@oskaremil 
probably class SQLiteTable is not part of package com.oeskeide.fairplaysquad.storage.helper.
Change the package string in «new Reflections("...")» to the package of type SQLiteTable.
"a convenient constructor for scanning within a package prefix"

**Comment by oskaremil** [comment]
It isn't. I thought the package prefix was to find the subtypes. 

Thanks for the tip. I'll try that, and if it does not work I will continue the thread on https://groups.google.com/forum/#!forum/google-code-reflections
