### ISSUE TITLE
Debugging logging isn't specifying the caught exception properly

### ISSUE THREAD

**Issue by kennymacleod** [ronmamo/reflections#83]
In the `Reflections::scan` method, there's the following logging statement:

    log.debug("could not scan file " + file.getRelativePath() + " in url " + url.toExternalForm() + 
                     " with scanner " + scanner.getClass().getSimpleName(), 
                     e.getMessage())

This intent of this would seem to be to log the exception message, but since there are no slf4j placeholders in the format string, it gets silently dropped.

This should either add a value placeholder to the string, or better yet replace `e.getMessage` with just `e`, which should make slf4j log the exception as a stack trace.

**Comment by ronmamo** [comment]
Merged
