### ISSUE TITLE
Publish current version to Maven

### ISSUE THREAD

**Issue by jakubhava** [ronmamo/reflections#87]
Hi,
  we are using the library for our project, but only the latest version currently on Github works for us. The current version published on Maven ( 0.9.10) contains a bug which keeps stopping our application.

Would it be possible to publish the current state of the project as is here on the github at the moment on the Maven so we can simply use it as a dependency ?

Thank you!

**Comment by martin-g** [comment]
You can use http://jitpack.io as a workaround until there is an official
release.

**Comment by MadMan0708** [comment]
Thanks!
