### ISSUE TITLE
ConfigurationBuilder useParallelExecutor() creates thread pool of "user" threads

### ISSUE THREAD

**Issue by markkolich** [ronmamo/reflections#89]
I'm using org.reflections `0.9.10` heavily in https://github.com/markkolich/curacao.  In a recent version of my app, I began setting `useParallelExecutor()` on my org.reflections `ConfigurationBuilder` like so:

``` java
public static final Reflections getTypeReflectionInstanceForPackage(final String pkg) {
  return new Reflections(new ConfigurationBuilder()
    .setUrls(ClasspathHelper.forPackage(pkg))
    .useParallelExecutor()
    .setScanners(new TypeAnnotationsScanner(), new SubTypesScanner()));
}
```

I noticed my app wasn't shutting down cleanly and so I went digging &mdash; I found a bunch of non-daemon threads were being spawned by reflections through my use of `useParallelExecutor()` and so on graceful shutdown my app was blocked waiting on these user threads to "stop" before the JVM would terminate.

I noticed that `useParallelExecutor()` without any arguments news up an internal fixed thread pool backed by the number of processors available to the JVM:

https://github.com/ronmamo/reflections/blob/master/src/main/java/org/reflections/util/ConfigurationBuilder.java#L249

``` java
public ConfigurationBuilder useParallelExecutor(final int availableProcessors) {
  setExecutorService(Executors.newFixedThreadPool(availableProcessors));
  return this;
}
```

This is fine except that the threads spawned by this fixed thread pool are not daemon threads.  And, because this thread pool is "internal" to `org.reflections` there's no way for me as a consumer to "access it" and call `executor.shutdown()` on it to stop the pool so my app can exit gracefully.

I think a better approach would be to either:
- Remove `useParallelExecutor()` and `useParallelExecutor(final int availableProcessors)` forcing the consumer to pass their own `Executor` instance.  That way, if they make a mistake, it's on the consumer to fix their own bug.
- Or, just make the pool spawn daemon threads by default using something like Guava's `ThreadFactoryBuilder` like so:

``` java
import com.google.common.util.concurrent.ThreadFactoryBuilder;

public ConfigurationBuilder useParallelExecutor(final int availableProcessors) {
  setExecutorService(Executors.newFixedThreadPool(availableProcessors,
    new ThreadFactoryBuilder().setDaemon(true).setNameFormat("org.reflections-%d").build()
  ));
  return this;
}
```

I'd also suggest using `setNameFormat` too, so when users are looking at thread dumps they can easily identify the threads spawned by `org.reflections` for parallel scanning.

**Comment by ronmamo** [comment]
agree. plus, the pool can be shut down right after scanning is finished. want to PR?

**Comment by markkolich** [comment]
@ronmamo sure, I'll submit a PR later today.

**Comment by markkolich** [comment]
@ronmamo here ya go: https://github.com/ronmamo/reflections/pull/90
